# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import src.proto.Comment_pb2 as Comment__pb2


class CreateCommentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateComment = channel.unary_unary(
        '/CreateComment/CreateComment',
        request_serializer=Comment__pb2.Comment.SerializeToString,
        response_deserializer=Comment__pb2.CommentResponse.FromString,
        )


class CreateCommentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateComment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CreateCommentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateComment': grpc.unary_unary_rpc_method_handler(
          servicer.CreateComment,
          request_deserializer=Comment__pb2.Comment.FromString,
          response_serializer=Comment__pb2.CommentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CreateComment', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
