# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import User_pb2 as User__pb2


class CreateUserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/CreateUserService/CreateUser',
        request_serializer=User__pb2.User.SerializeToString,
        response_deserializer=User__pb2.UserResponse.FromString,
        )


class CreateUserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CreateUserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=User__pb2.User.FromString,
          response_serializer=User__pb2.UserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CreateUserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
