version: "2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # - xpack.security.enabled=false
    - "elasticsearch.cluster1.xpack.security.enabled: false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
    - 9200:9200
    - 9300:9300

  elasticsearch-plugin-install:
    image:  docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    command: "bash /docker-plugin-install.sh repository-s3 &"
    volumes:
    - ./docker/es6/plugins/:/usr/share/elasticsearch/plugins/
    - ./docker/docker-plugin-install.sh:/docker-plugin-install.sh

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka
    depends_on:
    - zookeeper
    links:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - 9092:9092

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    depends_on:
    - zookeeper
    - kafka
    links:
    - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
    - 8081:8081

  # Services automating data and schema recreation
  create-topic:
    image: confluentinc/cp-kafka:5.1.0
    entrypoint: /bin/bash
    container_name: create-topic
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #Append more topics here if needed
      KAFKA_CREATE_TOPICS: "users:1:1,comments:1:1,notifications:1:1,quickstart-status:1:1,quickstart-offsets:1:1,quickstart-config:1:1"
    depends_on:
      - kafka
    links:
    - zookeeper
    - kafka
    volumes:
    - "./docker/create-topic.sh:/create-topic.sh"
    - "./docker/wait-for/wait-for:/wait-for"
    command: /wait-for kafka:9092 -t 100000 -- '/create-topic.sh'

    


